# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=128)),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=30, null=True)),
                ('Infos', models.TextField(null=True)),
                ('Status', models.CharField(choices=[('Parent', 'Parent'), ('Sitter', 'Sitter'), ('Both', 'Both')], max_length=30)),
            ],
        ),
    ]
