# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Prices',
            field=models.FloatField(null=True),
        ),
    ]
