# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0003_auto_20191216_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reserved', models.BooleanField(default=False)),
            ],
        ),
    ]
