# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0004_disponibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilities',
            name='Date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='disponibilities',
            name='Duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='disponibilities',
            name='SitterId',
            field=models.IntegerField(null=True),
        ),
    ]
