# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0006_disponibilities_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilities',
            name='End',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='disponibilities',
            name='Start',
            field=models.FloatField(null=True),
        ),
    ]
