# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0008_auto_20191216_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilities',
            name='By',
            field=models.IntegerField(null=True),
        ),
    ]
