# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Link',
            field=models.TextField(null=True),
        ),
    ]
