# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0011_message_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Target',
            field=models.IntegerField(null=True),
        ),
    ]
