# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0013_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(null=True)),
                ('Parent', models.IntegerField(null=True)),
                ('Sex', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('X', 'X')], max_length=30)),
                ('Infos', models.TextField(null=True)),
            ],
        ),
    ]
