# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0014_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.IntegerField(null=True)),
                ('FavoriteUser', models.IntegerField(null=True)),
            ],
        ),
    ]
