# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0015_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
