# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0016_child_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilities',
            name='ChildMax',
            field=models.IntegerField(null=True),
        ),
    ]
