# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0017_disponibilities_childmax'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilities',
            name='City',
            field=models.TextField(null=True),
        ),
    ]
