# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-18 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitters', '0019_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Admin',
            field=models.BooleanField(default=False),
        ),
    ]
